In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing
from IPython.display import Image, display
#from utils import plot_decision

In [2]:
df = pd.read_csv('car_evaluation.csv', header=None)
df.head(5)

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [3]:
df.columns = ['Buying', 'Maint', 'Doors','Persons','LugBoot','Safety','Evaluation']

In [4]:
df.head(5)

Buying  Maint Doors Persons LugBoot Safety Evaluation
0  vhigh  vhigh     2       2   small    low      unacc
1  vhigh  vhigh     2       2   small    med      unacc
2  vhigh  vhigh     2       2   small   high      unacc
3  vhigh  vhigh     2       2     med    low      unacc
4  vhigh  vhigh     2       2     med    med      unacc

In [5]:
df.describe()

Buying  Maint Doors Persons LugBoot Safety Evaluation
count    1728   1728  1728    1728    1728   1728       1728
unique      4      4     4       3       3      3          4
top     vhigh  vhigh     2       2   small    low      unacc
freq      432    432   432     576     576    576       1210

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Buying      1728 non-null   object
 1   Maint       1728 non-null   object
 2   Doors       1728 non-null   object
 3   Persons     1728 non-null   object
 4   LugBoot     1728 non-null   object
 5   Safety      1728 non-null   object
 6   Evaluation  1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [7]:
df['Buying'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [8]:
# Import label encoder
from sklearn import preprocessing

# Create a label encoder object
label_encoder = preprocessing.LabelEncoder()

# Encode labels in the 'Country' column
df['Buying'] = label_encoder.fit_transform(df['Buying'])

In [9]:
df['Buying'].unique()

array([3, 0, 2, 1])

In [10]:
df['Maint'] = label_encoder.fit_transform(df['Maint'])
df['LugBoot'] = label_encoder.fit_transform(df['LugBoot'])
df['Safety'] = label_encoder.fit_transform(df['Safety'])

In [11]:
df.head()

Buying  Maint Doors Persons  LugBoot  Safety Evaluation
0       3      3     2       2        2       1      unacc
1       3      3     2       2        2       2      unacc
2       3      3     2       2        2       0      unacc
3       3      3     2       2        1       1      unacc
4       3      3     2       2        1       2      unacc

In [12]:
df.LugBoot.unique()

array([2, 1, 0])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Buying      1728 non-null   int32 
 1   Maint       1728 non-null   int32 
 2   Doors       1728 non-null   object
 3   Persons     1728 non-null   object
 4   LugBoot     1728 non-null   int32 
 5   Safety      1728 non-null   int32 
 6   Evaluation  1728 non-null   object
dtypes: int32(4), object(3)
memory usage: 67.6+ KB


In [14]:
df.Doors.unique()

array(['2', '3', '4', '5more'], dtype=object)

In [15]:
df.Persons.unique()

array(['2', '4', 'more'], dtype=object)

In [16]:
df.Persons.replace('more', '6', inplace=True)

In [17]:
df.Persons.unique()

array(['2', '4', '6'], dtype=object)

In [18]:
df.Persons.unique()

array(['2', '4', '6'], dtype=object)

In [19]:
df.Persons=df.Persons.astype('int32')

In [20]:
df.Persons.unique()

array([2, 4, 6])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Buying      1728 non-null   int32 
 1   Maint       1728 non-null   int32 
 2   Doors       1728 non-null   object
 3   Persons     1728 non-null   int32 
 4   LugBoot     1728 non-null   int32 
 5   Safety      1728 non-null   int32 
 6   Evaluation  1728 non-null   object
dtypes: int32(5), object(2)
memory usage: 60.9+ KB


In [22]:
df.Doors.unique()

array(['2', '3', '4', '5more'], dtype=object)

In [23]:
df.Doors.replace('5more', '5',inplace  = True)

In [24]:
df.Doors=df.Doors.astype('int32')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Buying      1728 non-null   int32 
 1   Maint       1728 non-null   int32 
 2   Doors       1728 non-null   int32 
 3   Persons     1728 non-null   int32 
 4   LugBoot     1728 non-null   int32 
 5   Safety      1728 non-null   int32 
 6   Evaluation  1728 non-null   object
dtypes: int32(6), object(1)
memory usage: 54.1+ KB


In [26]:
X = df.drop('Evaluation', axis=1)
y = df['Evaluation']

In [29]:
df.head()

Buying  Maint  Doors  Persons  LugBoot  Safety Evaluation
0       3      3      2        2        2       1      unacc
1       3      3      2        2        2       2      unacc
2       3      3      2        2        2       0      unacc
3       3      3      2        2        1       1      unacc
4       3      3      2        2        1       2      unacc

In [30]:
dfarray = X.to_numpy()

In [31]:
dfarraytarget = y.to_numpy()

In [32]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Logistic Regression
l_scores = cross_val_score(LogisticRegression(), dfarray, dfarraytarget)
l_scores

C:\Tools\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Tools\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_opt

array([0.63294798, 0.65028902, 0.60115607, 0.67826087, 0.68115942])

In [33]:
np.average(l_scores)

0.6487626706877776

In [34]:
d_scores = cross_val_score(DecisionTreeClassifier(), dfarray, dfarraytarget)
d_scores

array([0.58092486, 0.83236994, 0.78034682, 0.86086957, 0.87536232])

In [35]:
np.average(d_scores)

0.7859747005110161

In [36]:
s_scores = cross_val_score(SVC(), dfarray, dfarraytarget)
s_scores

array([0.71387283, 0.78612717, 0.55202312, 0.77971014, 0.68695652])

In [37]:
np.average(s_scores)

0.70373795761079

In [38]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), dfarray, dfarraytarget)
r_scores

array([0.69653179, 0.81213873, 0.84682081, 0.84057971, 0.89855072])

In [39]:
np.average(r_scores)

0.8189243528524756

# Best Score is From Random Forest Classifier: 0.8189243528524756